### ISSUE TITLE
python Example on Web Auth API gives an error

### ISSUE THREAD

**Issue by sunchaser68** [wavesplatform/waves-documentation#1402]
Running the python example on Waves Auth API gives the following error:

```
Address: 3PCAB4sHXgvtu5NPoen6EXR5yaNbvsEA8Fj
Public key: 2M25DqL2W4rGFLCFadgATboS8EPqyWAN3DjH12AH5Kdr
Signed Data: b'\x00\x19WavesWalletAuthentication\x00\x0bexample.com\x00\r0123456789abc'
Real signature: 2w7QKSkxKEUwCVhx2VGrt5YiYVtAdoBZ8KQcxuNjGfN6n4fi1bn7PfPTnmdygZ6d87WhSXF1B9hW2pSmP7HucVbh
Verified: True
Traceback (most recent call last):
  File "a.py", line 51, in <module>
    print('Address verified:', verifyAddress(pub_key, address))
  File "a.py", line 31, in verifyAddress
    return address_from_public_key.decode() == address
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by mxmaslin** [comment]
Hi, sunchaser68. The example contains minor bug: it must be

    `return address_from_public_key == address`

instead of 

    `return address_from_public_key.decode() == address`

The code example is now fixed. Please let me know if you have another issue.

**Comment by sunchaser68** [comment]
I confirm it works:

```
$ python3.6 a.py
Address: 3PCAB4sHXgvtu5NPoen6EXR5yaNbvsEA8Fj
Public key: 2M25DqL2W4rGFLCFadgATboS8EPqyWAN3DjH12AH5Kdr
Signed Data: b'\x00\x19WavesWalletAuthentication\x00\x0bexample.com\x00\r0123456789abc'
Real signature: 2w7QKSkxKEUwCVhx2VGrt5YiYVtAdoBZ8KQcxuNjGfN6n4fi1bn7PfPTnmdygZ6d87WhSXF1B9hW2pSmP7HucVbh
Verified: True
Address verified: True
Fake signature: 29qWReHU9RXrQdQyXVXVciZarWXu7DXwekyV1zPivkrAzf4VSHb2Aq2FCKgRkKSozHFknKeq99dQaSmkhUDtZWsw
Fake signature verification: False

```
